/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/root'
import { Route as errorDefaultErrorRoutesRouteImport } from './pages/error/default-error/routes'
import { Route as middlewaresRestrictLoginSignupRouteImport } from './pages/middlewares/restrict-login-signup'
import { Route as middlewaresAuthenticateRouteImport } from './pages/middlewares/authenticate'
import { Route as error500RoutesRouteImport } from './pages/error/500/routes'
import { Route as error404RoutesRouteImport } from './pages/error/404/routes'
import { Route as error403RoutesRouteImport } from './pages/error/403/routes'
import { Route as indexRouteImport } from './pages/index'
import { Route as publicPrivacyPolicyRoutesRouteImport } from './pages/public/privacy-policy/routes'
import { Route as authLoginRoutesRouteImport } from './pages/auth/login/routes'
import { Route as authForgotPasswordRoutesRouteImport } from './pages/auth/forgot-password/routes'
import { Route as app_authenticatedLayoutRouteImport } from './pages/app/(_authenticated)/layout'
import { Route as app_authenticatedSupportsRoutesRouteImport } from './pages/app/(_authenticated)/supports/routes'
import { Route as app_authenticatedSettingsRoutesRouteImport } from './pages/app/(_authenticated)/settings/routes'
import { Route as app_authenticatedProfileRoutesRouteImport } from './pages/app/(_authenticated)/profile/routes'
import { Route as app_authenticatedDashboardRoutesRouteImport } from './pages/app/(_authenticated)/dashboard/routes'
import { Route as middlewaresRequireAdminRouteImport } from './pages/middlewares/require-admin'
import { Route as appadminLayoutRouteImport } from './pages/app/(admin)/layout'
import { Route as appadminReportsTimeSpendAnalyticRoutesRouteImport } from './pages/app/(admin)/reports/time-spend-analytic/routes'
import { Route as appadminReportsCompletionRatioRoutesRouteImport } from './pages/app/(admin)/reports/completion-ratio/routes'

const errorDefaultErrorRoutesRoute = errorDefaultErrorRoutesRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const middlewaresRestrictLoginSignupRoute =
  middlewaresRestrictLoginSignupRouteImport.update({
    id: '/_restrict-login-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const middlewaresAuthenticateRoute = middlewaresAuthenticateRouteImport.update({
  id: '/_authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const error500RoutesRoute = error500RoutesRouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const error404RoutesRoute = error404RoutesRouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const error403RoutesRoute = error403RoutesRouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyPolicyRoutesRoute =
  publicPrivacyPolicyRoutesRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => middlewaresRestrictLoginSignupRoute,
  } as any)
const authLoginRoutesRoute = authLoginRoutesRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => middlewaresRestrictLoginSignupRoute,
} as any)
const authForgotPasswordRoutesRoute =
  authForgotPasswordRoutesRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => middlewaresRestrictLoginSignupRoute,
  } as any)
const app_authenticatedLayoutRoute = app_authenticatedLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => middlewaresAuthenticateRoute,
} as any)
const app_authenticatedSupportsRoutesRoute =
  app_authenticatedSupportsRoutesRouteImport.update({
    id: '/supports',
    path: '/supports',
    getParentRoute: () => app_authenticatedLayoutRoute,
  } as any)
const app_authenticatedSettingsRoutesRoute =
  app_authenticatedSettingsRoutesRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => app_authenticatedLayoutRoute,
  } as any)
const app_authenticatedProfileRoutesRoute =
  app_authenticatedProfileRoutesRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => app_authenticatedLayoutRoute,
  } as any)
const app_authenticatedDashboardRoutesRoute =
  app_authenticatedDashboardRoutesRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => app_authenticatedLayoutRoute,
  } as any)
const middlewaresRequireAdminRoute = middlewaresRequireAdminRouteImport.update({
  id: '/_require-admin',
  getParentRoute: () => app_authenticatedLayoutRoute,
} as any)
const appadminLayoutRoute = appadminLayoutRouteImport.update({
  id: '/_admin-layout',
  getParentRoute: () => middlewaresRequireAdminRoute,
} as any)
const appadminReportsTimeSpendAnalyticRoutesRoute =
  appadminReportsTimeSpendAnalyticRoutesRouteImport.update({
    id: '/reports/time-spend-analytic',
    path: '/reports/time-spend-analytic',
    getParentRoute: () => appadminLayoutRoute,
  } as any)
const appadminReportsCompletionRatioRoutesRoute =
  appadminReportsCompletionRatioRoutesRouteImport.update({
    id: '/reports/completion-ratio',
    path: '/reports/completion-ratio',
    getParentRoute: () => appadminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/error': typeof errorDefaultErrorRoutesRoute
  '/forgot-password': typeof authForgotPasswordRoutesRoute
  '/login': typeof authLoginRoutesRoute
  '/privacy-policy': typeof publicPrivacyPolicyRoutesRoute
  '/dashboard': typeof app_authenticatedDashboardRoutesRoute
  '/profile': typeof app_authenticatedProfileRoutesRoute
  '/settings': typeof app_authenticatedSettingsRoutesRoute
  '/supports': typeof app_authenticatedSupportsRoutesRoute
  '/reports/completion-ratio': typeof appadminReportsCompletionRatioRoutesRoute
  '/reports/time-spend-analytic': typeof appadminReportsTimeSpendAnalyticRoutesRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/error': typeof errorDefaultErrorRoutesRoute
  '/forgot-password': typeof authForgotPasswordRoutesRoute
  '/login': typeof authLoginRoutesRoute
  '/privacy-policy': typeof publicPrivacyPolicyRoutesRoute
  '/dashboard': typeof app_authenticatedDashboardRoutesRoute
  '/profile': typeof app_authenticatedProfileRoutesRoute
  '/settings': typeof app_authenticatedSettingsRoutesRoute
  '/supports': typeof app_authenticatedSupportsRoutesRoute
  '/reports/completion-ratio': typeof appadminReportsCompletionRatioRoutesRoute
  '/reports/time-spend-analytic': typeof appadminReportsTimeSpendAnalyticRoutesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/403': typeof error403RoutesRoute
  '/404': typeof error404RoutesRoute
  '/500': typeof error500RoutesRoute
  '/_authenticate': typeof middlewaresAuthenticateRouteWithChildren
  '/_restrict-login-signup': typeof middlewaresRestrictLoginSignupRouteWithChildren
  '/error': typeof errorDefaultErrorRoutesRoute
  '/_authenticate/_app-layout': typeof app_authenticatedLayoutRouteWithChildren
  '/_restrict-login-signup/forgot-password': typeof authForgotPasswordRoutesRoute
  '/_restrict-login-signup/login': typeof authLoginRoutesRoute
  '/_restrict-login-signup/privacy-policy': typeof publicPrivacyPolicyRoutesRoute
  '/_authenticate/_app-layout/_require-admin': typeof middlewaresRequireAdminRouteWithChildren
  '/_authenticate/_app-layout/dashboard': typeof app_authenticatedDashboardRoutesRoute
  '/_authenticate/_app-layout/profile': typeof app_authenticatedProfileRoutesRoute
  '/_authenticate/_app-layout/settings': typeof app_authenticatedSettingsRoutesRoute
  '/_authenticate/_app-layout/supports': typeof app_authenticatedSupportsRoutesRoute
  '/_authenticate/_app-layout/_require-admin/_admin-layout': typeof appadminLayoutRouteWithChildren
  '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/completion-ratio': typeof appadminReportsCompletionRatioRoutesRoute
  '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/time-spend-analytic': typeof appadminReportsTimeSpendAnalyticRoutesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/supports'
    | '/reports/completion-ratio'
    | '/reports/time-spend-analytic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/privacy-policy'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/supports'
    | '/reports/completion-ratio'
    | '/reports/time-spend-analytic'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/_authenticate'
    | '/_restrict-login-signup'
    | '/error'
    | '/_authenticate/_app-layout'
    | '/_restrict-login-signup/forgot-password'
    | '/_restrict-login-signup/login'
    | '/_restrict-login-signup/privacy-policy'
    | '/_authenticate/_app-layout/_require-admin'
    | '/_authenticate/_app-layout/dashboard'
    | '/_authenticate/_app-layout/profile'
    | '/_authenticate/_app-layout/settings'
    | '/_authenticate/_app-layout/supports'
    | '/_authenticate/_app-layout/_require-admin/_admin-layout'
    | '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/completion-ratio'
    | '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/time-spend-analytic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  error403RoutesRoute: typeof error403RoutesRoute
  error404RoutesRoute: typeof error404RoutesRoute
  error500RoutesRoute: typeof error500RoutesRoute
  middlewaresAuthenticateRoute: typeof middlewaresAuthenticateRouteWithChildren
  middlewaresRestrictLoginSignupRoute: typeof middlewaresRestrictLoginSignupRouteWithChildren
  errorDefaultErrorRoutesRoute: typeof errorDefaultErrorRoutesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof errorDefaultErrorRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restrict-login-signup': {
      id: '/_restrict-login-signup'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof middlewaresRestrictLoginSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticate': {
      id: '/_authenticate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof middlewaresAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof error500RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof error404RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof error403RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_restrict-login-signup/privacy-policy': {
      id: '/_restrict-login-signup/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof publicPrivacyPolicyRoutesRouteImport
      parentRoute: typeof middlewaresRestrictLoginSignupRoute
    }
    '/_restrict-login-signup/login': {
      id: '/_restrict-login-signup/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRoutesRouteImport
      parentRoute: typeof middlewaresRestrictLoginSignupRoute
    }
    '/_restrict-login-signup/forgot-password': {
      id: '/_restrict-login-signup/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRoutesRouteImport
      parentRoute: typeof middlewaresRestrictLoginSignupRoute
    }
    '/_authenticate/_app-layout': {
      id: '/_authenticate/_app-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof app_authenticatedLayoutRouteImport
      parentRoute: typeof middlewaresAuthenticateRoute
    }
    '/_authenticate/_app-layout/supports': {
      id: '/_authenticate/_app-layout/supports'
      path: '/supports'
      fullPath: '/supports'
      preLoaderRoute: typeof app_authenticatedSupportsRoutesRouteImport
      parentRoute: typeof app_authenticatedLayoutRoute
    }
    '/_authenticate/_app-layout/settings': {
      id: '/_authenticate/_app-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof app_authenticatedSettingsRoutesRouteImport
      parentRoute: typeof app_authenticatedLayoutRoute
    }
    '/_authenticate/_app-layout/profile': {
      id: '/_authenticate/_app-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof app_authenticatedProfileRoutesRouteImport
      parentRoute: typeof app_authenticatedLayoutRoute
    }
    '/_authenticate/_app-layout/dashboard': {
      id: '/_authenticate/_app-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof app_authenticatedDashboardRoutesRouteImport
      parentRoute: typeof app_authenticatedLayoutRoute
    }
    '/_authenticate/_app-layout/_require-admin': {
      id: '/_authenticate/_app-layout/_require-admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof middlewaresRequireAdminRouteImport
      parentRoute: typeof app_authenticatedLayoutRoute
    }
    '/_authenticate/_app-layout/_require-admin/_admin-layout': {
      id: '/_authenticate/_app-layout/_require-admin/_admin-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appadminLayoutRouteImport
      parentRoute: typeof middlewaresRequireAdminRoute
    }
    '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/time-spend-analytic': {
      id: '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/time-spend-analytic'
      path: '/reports/time-spend-analytic'
      fullPath: '/reports/time-spend-analytic'
      preLoaderRoute: typeof appadminReportsTimeSpendAnalyticRoutesRouteImport
      parentRoute: typeof appadminLayoutRoute
    }
    '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/completion-ratio': {
      id: '/_authenticate/_app-layout/_require-admin/_admin-layout/reports/completion-ratio'
      path: '/reports/completion-ratio'
      fullPath: '/reports/completion-ratio'
      preLoaderRoute: typeof appadminReportsCompletionRatioRoutesRouteImport
      parentRoute: typeof appadminLayoutRoute
    }
  }
}

interface appadminLayoutRouteChildren {
  appadminReportsCompletionRatioRoutesRoute: typeof appadminReportsCompletionRatioRoutesRoute
  appadminReportsTimeSpendAnalyticRoutesRoute: typeof appadminReportsTimeSpendAnalyticRoutesRoute
}

const appadminLayoutRouteChildren: appadminLayoutRouteChildren = {
  appadminReportsCompletionRatioRoutesRoute:
    appadminReportsCompletionRatioRoutesRoute,
  appadminReportsTimeSpendAnalyticRoutesRoute:
    appadminReportsTimeSpendAnalyticRoutesRoute,
}

const appadminLayoutRouteWithChildren = appadminLayoutRoute._addFileChildren(
  appadminLayoutRouteChildren,
)

interface middlewaresRequireAdminRouteChildren {
  appadminLayoutRoute: typeof appadminLayoutRouteWithChildren
}

const middlewaresRequireAdminRouteChildren: middlewaresRequireAdminRouteChildren =
  {
    appadminLayoutRoute: appadminLayoutRouteWithChildren,
  }

const middlewaresRequireAdminRouteWithChildren =
  middlewaresRequireAdminRoute._addFileChildren(
    middlewaresRequireAdminRouteChildren,
  )

interface app_authenticatedLayoutRouteChildren {
  middlewaresRequireAdminRoute: typeof middlewaresRequireAdminRouteWithChildren
  app_authenticatedDashboardRoutesRoute: typeof app_authenticatedDashboardRoutesRoute
  app_authenticatedProfileRoutesRoute: typeof app_authenticatedProfileRoutesRoute
  app_authenticatedSettingsRoutesRoute: typeof app_authenticatedSettingsRoutesRoute
  app_authenticatedSupportsRoutesRoute: typeof app_authenticatedSupportsRoutesRoute
}

const app_authenticatedLayoutRouteChildren: app_authenticatedLayoutRouteChildren =
  {
    middlewaresRequireAdminRoute: middlewaresRequireAdminRouteWithChildren,
    app_authenticatedDashboardRoutesRoute:
      app_authenticatedDashboardRoutesRoute,
    app_authenticatedProfileRoutesRoute: app_authenticatedProfileRoutesRoute,
    app_authenticatedSettingsRoutesRoute: app_authenticatedSettingsRoutesRoute,
    app_authenticatedSupportsRoutesRoute: app_authenticatedSupportsRoutesRoute,
  }

const app_authenticatedLayoutRouteWithChildren =
  app_authenticatedLayoutRoute._addFileChildren(
    app_authenticatedLayoutRouteChildren,
  )

interface middlewaresAuthenticateRouteChildren {
  app_authenticatedLayoutRoute: typeof app_authenticatedLayoutRouteWithChildren
}

const middlewaresAuthenticateRouteChildren: middlewaresAuthenticateRouteChildren =
  {
    app_authenticatedLayoutRoute: app_authenticatedLayoutRouteWithChildren,
  }

const middlewaresAuthenticateRouteWithChildren =
  middlewaresAuthenticateRoute._addFileChildren(
    middlewaresAuthenticateRouteChildren,
  )

interface middlewaresRestrictLoginSignupRouteChildren {
  authForgotPasswordRoutesRoute: typeof authForgotPasswordRoutesRoute
  authLoginRoutesRoute: typeof authLoginRoutesRoute
  publicPrivacyPolicyRoutesRoute: typeof publicPrivacyPolicyRoutesRoute
}

const middlewaresRestrictLoginSignupRouteChildren: middlewaresRestrictLoginSignupRouteChildren =
  {
    authForgotPasswordRoutesRoute: authForgotPasswordRoutesRoute,
    authLoginRoutesRoute: authLoginRoutesRoute,
    publicPrivacyPolicyRoutesRoute: publicPrivacyPolicyRoutesRoute,
  }

const middlewaresRestrictLoginSignupRouteWithChildren =
  middlewaresRestrictLoginSignupRoute._addFileChildren(
    middlewaresRestrictLoginSignupRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  error403RoutesRoute: error403RoutesRoute,
  error404RoutesRoute: error404RoutesRoute,
  error500RoutesRoute: error500RoutesRoute,
  middlewaresAuthenticateRoute: middlewaresAuthenticateRouteWithChildren,
  middlewaresRestrictLoginSignupRoute:
    middlewaresRestrictLoginSignupRouteWithChildren,
  errorDefaultErrorRoutesRoute: errorDefaultErrorRoutesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
